name: Full-year calendar
  with:
    filename: metrics.plugin.isocalendar.fullyear.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_isocalendar: yes
    plugin_isocalendar_duration: full-year
